#!/usr/bin/env bash
# =============================================================================
# show_histogram.sh -- summarise the CHM_NUMERICAL catalog into a markdown
#                      report of (d, #Lambda) statistics.
# ./show_histogram.sh && glow dL_statistic.md
#
# *.tsv is a result of 
# ./search_chm.sh --count 10000 --size 11 --lmin 1 --lmax 5700 --symmetry s
#
# 2026-09-11  Claude Sonnet 5
# 2026-09-13  one catalog, CHM_NUMERICAL.tsv next to this script, replaces
#             the former chm_N*_*/index.tsv files
#
# Reads the single catalog written by search_chm.sh (tab separated:
# "#file N symmetry #L ud q attempt seed"), groups the recorded
# (d, #Lambda) pairs by (N, symmetry), and writes one table per group to
# dL_statistic.md: d, #L, and a 3rd column with the occurrence count and
# percentage.
#
# Only the catalog is read -- the *.m matrix files themselves are never
# opened, so this keeps working after they are deleted. Re-run any time the
# catalog grows; the output is fully regenerated from scratch each time.
#
#   ./show_histogram.sh               # writes dL_statistic.md
#   ./show_histogram.sh other.md      # writes to a different file
#   CATALOG=path/to.tsv ./show_histogram.sh    # read a different catalog
# =============================================================================

set -u -o pipefail
shopt -s nullglob

# force a fixed locale: makes sort ordering and printf's decimal point
# (period, not comma) consistent regardless of who/where this is run.
export LC_ALL=C

OUT="${1:-dL_statistic.md}"
HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
CATALOG="${CATALOG:-$HERE/CHM_NUMERICAL.tsv}"

if [ ! -s "$CATALOG" ]; then
    printf 'show_histogram.sh: no catalog at %s\n' "$CATALOG" >&2
    exit 2
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# ---- 1. gather every data row from the catalog: "N SYM d L" -------------
awk -F'\t' '$1 !~ /^#/ && $1 != "" {print $2, $3, $5, $4}' "$CATALOG" > "$TMP"

if [ ! -s "$TMP" ]; then
    {
        echo "# CHM (d, #Lambda) statistics"
        echo
        echo "No data rows found in \`$CATALOG\`."
    } > "$OUT"
    echo "no data found; wrote empty report to $OUT" >&2
    exit 0
fi

# the awk program shared by every (N, symmetry) group: reads "count d l"
# lines (already counted and sorted by d then #L) and emits a single
# markdown table with occurrence count + percentage in a 3rd column.
read -r -d '' AWK_GROUP <<'EOF'
{
    cnt[NR] = $1; d[NR] = $2; l[NR] = $3
    total += $1
    n = NR
}
END {
    print "| d | #L | count |"
    print "|---|----|-------|"
    for (i = 1; i <= n; i++) {
        pct = 100 * cnt[i] / total
        printf "| %s | %s | %d (%.1f%%) |\n", d[i], l[i], cnt[i], pct
    }
    print ""
}
EOF

# ---- 2. one (N, symmetry) group at a time, sorted by d then #L ----------
{
    echo "# CHM (d, #Lambda) statistics"
    echo
    echo "Generated by \`show_histogram.sh\` from \`$(basename -- "$CATALOG")\`."
    echo

    while read -r N SYM; do
        TOTAL_ROWS=$(awk -v n="$N" -v s="$SYM" '$1==n && $2==s' "$TMP" | wc -l)
        echo "## N = ${N}, symmetry = ${SYM}  (${TOTAL_ROWS} samples)"
        echo

        awk -v n="$N" -v s="$SYM" '$1==n && $2==s {print $3, $4}' "$TMP" \
            | sort | uniq -c | sort -k2,2n -k3,3n \
            | awk "$AWK_GROUP"
    done < <(awk '{print $1, $2}' "$TMP" | sort -u -k1,1n -k2,2)

} > "$OUT"

echo "wrote $OUT"
